---
- name: Remove earlier image blueprint repo clone
  ansible.builtin.file:
    path: "{{ rhel_image_local_repo_path }}"
    state: absent

- name: Fail if old misleading size parameter is used
  ansible.builtin.fail:
    msg: "Use 'rhel_image_size' (in MiB), not 'rhel_image_size_kb' (was also in MiB)."
  when: rhel_image_size_kb is defined

- name: Clone image blueprint repo
  ansible.builtin.git:
    repo: "{{ rhel_image_git_remote_repo }}"
    dest: "{{ rhel_image_local_repo_path }}"
    version: "{{ rhel_image_git_repo_checkout }}"
    key_file: "{{ rhel_image_git_key_file | default(omit) }}"
    accept_newhostkey: true

- name: Push image blueprint to osbuilder
  ansible.builtin.command:
    cmd: composer-cli blueprints push {{ rhel_image_blueprint }}.toml
    chdir: "{{ rhel_image_local_repo_path }}"
  changed_when: true

- name: Verify image blueprint
  ansible.builtin.command: composer-cli blueprints depsolve {{ rhel_image_blueprint }}
  changed_when: true

- name: Start image build
  vars:
    __rhi_ostree_ref: "{{ rhel_image_ostree_ref | default(false) }}"
    __rhi_ref_option: "{{ __rhi_ostree_ref | ternary('--ref ' + __rhi_ostree_ref | string, '') }}"
    __rhi_ostree_parent: "{{ rhel_image_ostree_parent | default(false) }}"
    __rhi_parent_option: "{{ __rhi_ostree_parent | ternary('--parent ' + __rhi_ostree_parent | string, '') }}"
    __rhi_ostree_url: "{{ rhel_image_ostree_url | default(false) }}"
    __rhi_url_option: "{{ __rhi_ostree_url | ternary('--url ' + __rhi_ostree_url | string, '') }}"
    __rhi_size_mb: "{{ rhel_image_size | default(false) }}"
    __rhi_size_option: "{{ __rhi_size_mb | ternary('--size ' + __rhi_size_mb | string, '') }}"
    __rhi_start_cmd: "{{ 'start-ostree' if __rhi_ostree_ref else 'start' }}"
  ansible.builtin.command: >
    composer-cli compose
    {{ __rhi_start_cmd }} {{ __rhi_ref_option }} {{ __rhi_parent_option }} {{ __rhi_url_option }} {{ __rhi_size_option }}
    {{ rhel_image_blueprint }} {{ rhel_image_output_type }}
  register: __rhi_build_command
  changed_when: true

- name: Record build UUID
  ansible.builtin.set_fact:
    __rhi_build_uuid: "{{ (__rhi_build_command.stdout_lines | select('search', '^Compose ') | first).split()[1] }}"

- name: Wait for image build to complete
  ansible.builtin.command: composer-cli compose info {{ __rhi_build_uuid }}
  register: __rhi_build_status
  failed_when: "'not a valid build' in __rhi_build_status.stderr or 'FAILED' in __rhi_build_status.stdout"
  changed_when: false
  ignore_errors: true
  until: "'not a valid build' in __rhi_build_status.stderr or 'FAILED' in __rhi_build_status.stdout or 'FINISHED' in __rhi_build_status.stdout"
  retries: 30
  delay: 30

- name: Display failed build logs
  ansible.builtin.include_tasks: build_logs_display.yml
  when: "'not a valid build' in __rhi_build_status.stderr or 'FAILED' in __rhi_build_status.stdout"

- name: Fail if build not successful
  ansible.builtin.fail:
    msg: "Build failed."
  when: "'not a valid build' in __rhi_build_status.stderr or 'FAILED' in __rhi_build_status.stdout"

- name: Create image download directory
  ansible.builtin.file:
    state: directory
    # noqa: risky-file-permissions
    path: "{{ rhel_image_download_dir }}"

- name: Download image from osbuilder
  vars:
    __rhi_build_file: "{{ rhel_image_filename if rhel_image_filename else __rhi_build_uuid }}"
    __rhi_cmd_params: "{{ '' if __rhi_build_file == __rhi_build_uuid else '--filename ' + __rhi_build_file }}"
  ansible.builtin.command:
    cmd: composer-cli compose image {{ __rhi_build_uuid }} {{ __rhi_cmd_params }}
    chdir: "{{ rhel_image_download_dir }}"
  register: __rhi_image_file
  changed_when: true

- name: Delete image build from osbuilder
  ansible.builtin.command: composer-cli compose delete {{ __rhi_build_uuid }}
  changed_when: true
  when: rhel_image_build_remove | bool

- name: Remove image blueprint repo clone
  ansible.builtin.file:
    path: "{{ rhel_image_local_repo_path }}"
    state: absent
