---
- name: Gather packages facts
  ansible.builtin.package_facts:

- name: Create Image Builder configuration directory
  ansible.builtin.file:
    path: /etc/osbuild-composer/repositories
    state: directory
    mode: '0755'
  when: rhel_image_use_satellite | bool

- name: Read system repository configuration
  vars:
    __rhi_rhel_ver: "{{ ansible_facts.distribution_major_version }}"
    __rhi_rhel_arch: "{{ ansible_facts.architecture }}"
  ansible.builtin.shell: >
    set -o pipefail &&
    grep -A 5 '^\[rhel-{{ __rhi_rhel_ver }}-for-{{ __rhi_rhel_arch }}-baseos-rpms\]' /etc/yum.repos.d/redhat.repo
    | awk '/baseurl/ {print $3}'
  register: __rhi_rhsm_baseurl
  changed_when: false
  when:
    - rhel_image_use_satellite | bool
    - rhel_image_repo_versions | default(false, true)

- name: Create basic repository configuration files
  vars:
    __rhi_baseos_repo_url: "{{ __rhi_rhsm_baseurl.stdout | replace('$releasever', item) }}"
    __rhi_appstream_repo_url: "{{ __rhi_rhsm_baseurl.stdout | replace('$releasever', item) | replace('baseos', 'appstream') }}"
  ansible.builtin.template:
    src: rhel-repo.json.j2
    dest: /etc/osbuild-composer/repositories/rhel-{{ item }}.json
    mode: '0644'
  register: __rhi_config_basic
  loop: "{{ rhel_image_repo_versions | default([], true) }}"
  when: rhel_image_use_satellite | bool

- name: Create custom repository configuration files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/osbuild-composer/repositories/{{ item | basename | replace('.j2', '') }}
    mode: '0644'
  register: __rhi_config_custom
  loop: "{{ rhel_image_repo_templates | default([], true) }}"
  when: rhel_image_use_satellite | bool

- name: Reboot system
  ansible.builtin.reboot:
  when:
    - "'osbuild-composer' in ansible_facts.packages"
    - __rhi_config_basic is changed or
      __rhi_config_custom is changed

- name: Install Image Builder
  ansible.builtin.dnf:
    name:
      - git-core
      - osbuild-composer
      - python3
      - tar
      - weldr-client
    state: present
  register: __rhi_builder_packages
  when: "'osbuild-composer' not in ansible_facts.packages"

- name: Update all packages
  # noqa: package-latest
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
  register: __rhi_package_update
  when: rhel_image_update_host | bool

- name: Enable Image Builder
  ansible.builtin.service:
    name: osbuild-composer.socket
    state: started
    enabled: true
  register: __rhi_builder_socket

- name: Create user for building images
  ansible.builtin.user:
    name: "{{ rhel_image_builder_user }}"
    groups: weldr
    append: true
  register: __rhi_user_create
  when: rhel_image_create_user | bool

- name: Reboot system
  ansible.builtin.reboot:
  when:
    - rhel_image_reboot_host | bool
    - __rhi_builder_packages is changed or
      __rhi_package_update is changed or
      __rhi_builder_socket is changed or
      __rhi_user_create is changed
