---
- name: Get list of builds
  ansible.builtin.command: composer-cli compose list
  register: __rhi_build_list
  changed_when: false

- name: Delete builds
  ansible.builtin.command: composer-cli compose delete {{ item | split | first }}
  register: __rhi_build_delete
  changed_when: true
  loop: "{{ __rhi_build_list.stdout_lines | reject('search', 'Status') }}"

- name: Wait for build deletion to complete
  ansible.builtin.pause:
    seconds: 10
  when: __rhi_build_delete is changed

# https://bugzilla.redhat.com/show_bug.cgi?id=2023280
- name: Get list of build artifacts to delete
  ansible.builtin.find:
    paths:
      - /var/cache/osbuild-worker/osbuild-store/stage
      - /var/cache/osbuild-worker/osbuild-store/tmp
      - /var/cache/osbuild-worker/output
      - /var/lib/osbuild-composer/artifacts/tmp
      - /var/lib/osbuild-composer/jobs
    file_type: any
    recurse: false
  register: __rhi_build_artifacts

# https://bugzilla.redhat.com/show_bug.cgi?id=2023280
- name: Delete build artifacts
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ __rhi_build_artifacts.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Get list of osbuilder temporary directories
  ansible.builtin.find:
    paths:
      - /tmp
      - /var/tmp
    file_type: directory
    patterns: 'dnf-_osbuild-composer*,tmp*'
    recurse: false
  register: __rhi_temp_directories

- name: Delete osbuilder temporary directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ __rhi_temp_directories.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.pw_name == '_osbuild-composer'
