---
- name: Create temporary directory for build logs
  ansible.builtin.tempfile:
    state: directory
    suffix: .logs
  register: __rhi_logs_directory

- name: Fetch build logs from osbuilder
  ansible.builtin.command:
    cmd: composer-cli compose logs {{ __rhi_build_uuid }}
    chdir: "{{ __rhi_logs_directory.path }}"
  changed_when: true

- name: Extract build logs archive
  ansible.builtin.unarchive:
    src: "{{ __rhi_logs_directory.path }}/{{ __rhi_build_uuid }}-logs.tar"
    dest: "{{ __rhi_logs_directory.path }}"
    remote_src: true

- name: Read complete build logs
  ansible.builtin.slurp:
    src: "{{ __rhi_logs_directory.path + '/logs/osbuild.log' }}"
  register: __rhi_log_content

- name: Display complete build logs
  ansible.builtin.debug:
    msg: "{{ __rhi_log_content.content | b64decode }}"

- name: Remove temporary logs directory
  ansible.builtin.file:
    path: "{{ __rhi_logs_directory.path }}"
    state: absent
